"""campos extras v3 mamada soneca fralda

Revision ID: 6216b2954162
Revises: f15d4d7a773e
Create Date: 2026-07-05 21:41:44.131086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6216b2954162'
down_revision: Union[str, None] = 'f15d4d7a773e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diapers', sa.Column('type', sa.String(), nullable=True))
    op.add_column('diapers', sa.Column('consistency', sa.String(), nullable=True))
    op.add_column('diapers', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('feedings', sa.Column('type', sa.String(), nullable=True))
    op.add_column('feedings', sa.Column('side', sa.String(), nullable=True))
    op.add_column('feedings', sa.Column('volume_ml', sa.Integer(), nullable=True))
    op.add_column('feedings', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('naps', sa.Column('location', sa.String(), nullable=True))
    op.add_column('naps', sa.Column('light_environment', sa.String(), nullable=True))
    op.add_column('naps', sa.Column('white_noise', sa.Boolean(), nullable=True))
    op.add_column('naps', sa.Column('note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('naps', 'note')
    op.drop_column('naps', 'white_noise')
    op.drop_column('naps', 'light_environment')
    op.drop_column('naps', 'location')
    op.drop_column('feedings', 'note')
    op.drop_column('feedings', 'volume_ml')
    op.drop_column('feedings', 'side')
    op.drop_column('feedings', 'type')
    op.drop_column('diapers', 'note')
    op.drop_column('diapers', 'consistency')
    op.drop_column('diapers', 'type')
    # ### end Alembic commands ###
